// Generated Bountiful order pools for the 15-level farm economy.
// High-priority data intentionally overrides the legacy level_1..8 pack and
// extends the same decree IDs through level_15 without shipping another binary zip.
ServerEvents.highPriorityData(event => {
    const rewardPools = {
        bh_copper_rews: { content: { copper_coin: { type: 'item', content: 'kubejs:copper_coin', amount: { min: 1, max: 16 }, unitWorth: 100 } } },
        bh_iron_rews: { content: { iron_coin: { type: 'item', content: 'kubejs:iron_coin', amount: { min: 1, max: 8 }, unitWorth: 900 } } },
        bh_gold_rews: { content: { gold_coin: { type: 'item', content: 'kubejs:gold_coin', amount: { min: 1, max: 4 }, unitWorth: 8100 } } }
    }

    Object.entries(rewardPools).forEach(([id, data]) => {
        event.addJson(`bountiful:bounty_pools/bountiful/${id}`, data)
    })

    const levels = {
        1: { reward: 'bh_copper_rews', content: { wheat: { type: 'item', content: 'minecraft:wheat', amount: { min: 4, max: 24 }, unitWorth: 40 }, bread: { type: 'item', content: 'minecraft:bread', amount: { min: 2, max: 12 }, unitWorth: 90 }, apple: { type: 'item', content: 'minecraft:apple', amount: { min: 2, max: 10 }, unitWorth: 70 } } },
        2: { reward: 'bh_copper_rews', content: { eggs: { type: 'item', content: 'minecraft:egg', amount: { min: 2, max: 12 }, unitWorth: 80 }, chicken: { type: 'item', content: 'minecraft:cooked_chicken', amount: { min: 2, max: 10 }, unitWorth: 130 }, charcoal: { type: 'item', content: 'minecraft:charcoal', amount: { min: 4, max: 20 }, unitWorth: 55 }, bread: { type: 'item', content: 'minecraft:bread', amount: { min: 2, max: 10 }, unitWorth: 90 } } },
        3: { reward: 'bh_copper_rews', content: { steak: { type: 'item', content: 'minecraft:cooked_beef', amount: { min: 2, max: 10 }, unitWorth: 170 }, leather: { type: 'item', content: 'minecraft:leather', amount: { min: 2, max: 12 }, unitWorth: 145 }, eggs: { type: 'item', content: 'minecraft:egg', amount: { min: 2, max: 12 }, unitWorth: 80 }, bread: { type: 'item', content: 'minecraft:bread', amount: { min: 2, max: 10 }, unitWorth: 90 } } },
        4: { reward: 'bh_copper_rews', content: { carrots: { type: 'item', content: 'minecraft:carrot', amount: { min: 4, max: 24 }, unitWorth: 65 }, pork: { type: 'item', content: 'minecraft:cooked_porkchop', amount: { min: 2, max: 12 }, unitWorth: 165 }, dough: { type: 'item', content: 'farmersdelight:wheat_dough', amount: { min: 2, max: 12 }, unitWorth: 120 }, bread: { type: 'item', content: 'minecraft:bread', amount: { min: 2, max: 12 }, unitWorth: 90 } } },
        5: { reward: 'bh_copper_rews', content: { cod: { type: 'item', content: 'minecraft:cod', amount: { min: 2, max: 12 }, unitWorth: 110 }, salmon: { type: 'item', content: 'minecraft:salmon', amount: { min: 2, max: 10 }, unitWorth: 125 }, fillet: { type: 'item', content: 'aquaculture:fish_fillet_raw', amount: { min: 2, max: 12 }, unitWorth: 140 }, seagrass_salad: { type: 'item', content: 'oceansdelight:seagrass_salad', amount: { min: 1, max: 8 }, unitWorth: 180 }, carrot: { type: 'item', content: 'minecraft:carrot', amount: { min: 4, max: 20 }, unitWorth: 65 } } },
        6: { reward: 'bh_copper_rews', content: { wool: { type: 'item', content: 'minecraft:white_wool', amount: { min: 2, max: 12 }, unitWorth: 125 }, potato: { type: 'item', content: 'minecraft:baked_potato', amount: { min: 3, max: 16 }, unitWorth: 100 }, yarn: { type: 'item', content: 'kubejs:wool_yarn', amount: { min: 2, max: 10 }, unitWorth: 185 }, sugar: { type: 'item', content: 'minecraft:sugar', amount: { min: 4, max: 20 }, unitWorth: 70 }, salmon: { type: 'item', content: 'minecraft:cooked_salmon', amount: { min: 2, max: 10 }, unitWorth: 150 } } },
        7: { reward: 'bh_iron_rews', content: { copper: { type: 'item', content: 'minecraft:copper_ingot', amount: { min: 2, max: 12 }, unitWorth: 220 }, iron: { type: 'item', content: 'minecraft:iron_ingot', amount: { min: 1, max: 8 }, unitWorth: 420 }, milk: { type: 'item', content: 'minecraft:milk_bucket', amount: { min: 1, max: 3 }, unitWorth: 420 }, apple_pie: { type: 'item', content: 'farmersdelight:apple_pie', amount: { min: 1, max: 5 }, unitWorth: 350 }, dough: { type: 'item', content: 'farmersdelight:wheat_dough', amount: { min: 2, max: 10 }, unitWorth: 120 } } },
        8: { reward: 'bh_iron_rews', content: { sandwich: { type: 'item', content: 'farmersdelight:chicken_sandwich', amount: { min: 1, max: 6 }, unitWorth: 420 }, breakfast: { type: 'item', content: 'farmersdelight:bacon_and_eggs', amount: { min: 1, max: 6 }, unitWorth: 390 }, cabbage: { type: 'item', content: 'farmersdelight:cabbage', amount: { min: 3, max: 16 }, unitWorth: 115 }, beef_patty: { type: 'item', content: 'farmersdelight:beef_patty', amount: { min: 2, max: 10 }, unitWorth: 220 }, potato: { type: 'item', content: 'minecraft:baked_potato', amount: { min: 3, max: 14 }, unitWorth: 100 } } },
        9: { reward: 'bh_iron_rews', content: { corn: { type: 'item', content: 'corn_delight:corn', amount: { min: 4, max: 24 }, unitWorth: 105 }, cornbread: { type: 'item', content: 'corn_delight:cornbread', amount: { min: 2, max: 10 }, unitWorth: 280 }, tortilla: { type: 'item', content: 'corn_delight:tortilla', amount: { min: 2, max: 12 }, unitWorth: 180 }, taco: { type: 'item', content: 'corn_delight:taco', amount: { min: 1, max: 6 }, unitWorth: 460 }, cabbage: { type: 'item', content: 'farmersdelight:cabbage', amount: { min: 3, max: 14 }, unitWorth: 115 } } },
        10: { reward: 'bh_iron_rews', content: { alloy: { type: 'item', content: 'create:andesite_alloy', amount: { min: 1, max: 8 }, unitWorth: 380 }, shaft: { type: 'item', content: 'create:shaft', amount: { min: 2, max: 12 }, unitWorth: 150 }, cogwheel: { type: 'item', content: 'create:cogwheel', amount: { min: 2, max: 10 }, unitWorth: 180 }, leather: { type: 'item', content: 'minecraft:leather', amount: { min: 2, max: 10 }, unitWorth: 145 }, corn: { type: 'item', content: 'corn_delight:corn', amount: { min: 6, max: 28 }, unitWorth: 105 }, wheat: { type: 'item', content: 'minecraft:wheat', amount: { min: 6, max: 28 }, unitWorth: 40 } } },
        11: { reward: 'bh_iron_rews', content: { pineapple: { type: 'item', content: 'pineapple_delight:pineapple', amount: { min: 3, max: 18 }, unitWorth: 160 }, pie: { type: 'item', content: 'pineapple_delight:pineapple_pie', amount: { min: 1, max: 6 }, unitWorth: 480 }, fried_rice: { type: 'item', content: 'pineapple_delight:pineapple_fried_rice', amount: { min: 1, max: 6 }, unitWorth: 520 }, juice: { type: 'item', content: 'pineapple_delight:pineapple_juice', amount: { min: 1, max: 8 }, unitWorth: 360 }, taco: { type: 'item', content: 'corn_delight:taco', amount: { min: 1, max: 5 }, unitWorth: 460 } } },
        12: { reward: 'bh_gold_rews', content: { motor: { type: 'item', content: 'createaddition:electric_motor', amount: { min: 1, max: 3 }, unitWorth: 950 }, alternator: { type: 'item', content: 'createaddition:alternator', amount: { min: 1, max: 3 }, unitWorth: 900 }, accumulator: { type: 'item', content: 'createaddition:accumulator', amount: { min: 1, max: 3 }, unitWorth: 850 }, gold: { type: 'item', content: 'minecraft:gold_ingot', amount: { min: 1, max: 8 }, unitWorth: 430 }, pineapple_pie: { type: 'item', content: 'pineapple_delight:pineapple_pie', amount: { min: 1, max: 5 }, unitWorth: 480 } } },
        13: { reward: 'bh_gold_rews', content: { bison_burger: { type: 'item', content: 'alexsdelight:bison_burger', amount: { min: 1, max: 6 }, unitWorth: 650 }, blossom_soup: { type: 'item', content: 'alexsdelight:acacia_blossom_soup', amount: { min: 1, max: 6 }, unitWorth: 580 }, pineapple_juice: { type: 'item', content: 'pineapple_delight:pineapple_juice', amount: { min: 1, max: 6 }, unitWorth: 360 }, motor: { type: 'item', content: 'createaddition:electric_motor', amount: { min: 1, max: 2 }, unitWorth: 950 }, cornbread: { type: 'item', content: 'corn_delight:cornbread', amount: { min: 2, max: 8 }, unitWorth: 280 } } },
        14: { reward: 'bh_gold_rews', content: { diamond: { type: 'item', content: 'minecraft:diamond', amount: { min: 1, max: 6 }, unitWorth: 1100 }, amethyst: { type: 'item', content: 'minecraft:amethyst_shard', amount: { min: 2, max: 12 }, unitWorth: 320 }, tablet: { type: 'item', content: 'alexscaves:cave_tablet', amount: { min: 1, max: 2 }, unitWorth: 1400 }, bison_burger: { type: 'item', content: 'alexsdelight:bison_burger', amount: { min: 1, max: 5 }, unitWorth: 650 }, sandwich: { type: 'item', content: 'farmersdelight:chicken_sandwich', amount: { min: 1, max: 5 }, unitWorth: 420 } } },
        15: { reward: 'bh_gold_rews', content: { magic_map: { type: 'item', content: 'twilightforest:magic_map', amount: { min: 1, max: 2 }, unitWorth: 1800 }, glowstew: { type: 'item', content: 'twilightdelight:glowstew', amount: { min: 1, max: 5 }, unitWorth: 720 }, diamond: { type: 'item', content: 'minecraft:diamond', amount: { min: 1, max: 5 }, unitWorth: 1100 }, taco: { type: 'item', content: 'corn_delight:taco', amount: { min: 1, max: 5 }, unitWorth: 460 }, pineapple_pie: { type: 'item', content: 'pineapple_delight:pineapple_pie', amount: { min: 1, max: 5 }, unitWorth: 480 }, bison_burger: { type: 'item', content: 'alexsdelight:bison_burger', amount: { min: 1, max: 5 }, unitWorth: 650 }, motor: { type: 'item', content: 'createaddition:electric_motor', amount: { min: 1, max: 2 }, unitWorth: 950 } } }
    }

    Object.entries(levels).forEach(([level, data]) => {
        const pool = `level_${level}_objs`
        event.addJson(`bountiful:bounty_pools/bountiful/${pool}`, { content: data.content })
        event.addJson(`bountiful:bounty_decrees/bountiful/level_${level}`, {
            linkedProfessions: ['farmer'],
            objectives: [pool],
            rewards: [data.reward]
        })
    })
})
